# Generated by Django 4.0.1 on 2022-01-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('color', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
