# Generated by Django 4.0.1 on 2022-01-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterField(
            model_name='notes',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blu', 'Blue'), ('org', 'Orange'), ('pur', 'Purple')], max_length=15),
        ),
    ]
