# Generated by Django 4.0.1 on 2022-01-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notes_options_alter_notes_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
