# Generated by Django 4.0.1 on 2022-01-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_notes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
