# Generated by Django 4.0.1 on 2022-01-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_notes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='color',
            field=models.CharField(choices=[('bg-red-200', 'Red'), ('bg-blue-200', 'Blue'), ('bg-orange-100', 'Orange'), ('bg-indigo-200', 'Purple')], max_length=15),
        ),
    ]
