# Generated by Django 4.0.1 on 2022-01-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_notes_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
